spring:
  profiles:
    active: dev

  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

  messages:
    basename: i18n.messages

#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false

  #数据库相关
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池配置
      initial-size: 1                                                  #初始化时建立物理连接的个数,缺省0
      max-active: 20                                                    #最大连接池数量，缺省8
      min-idle: 1                                                      #最小连接池数量
      max-wait: 60000                                                  #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      validation-query: select 'x'                                    #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #stat用于监控sql，wall用于防火墙
      filters: stat,wall

      #配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: hutao
        login-password: 123456
   #redis相关
#  redis:
#    host: 118.24.215.214
#    port: 6379
#    password: 123456
#    timeout: 30000
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0


# mybatis plus插件
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.aidancloud.demo.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_empty
